// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Aquarelas documents
 */
interface AquarelasDocumentData {
  /**
   * Título field in *Aquarelas*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aquarelas.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Conteúdo field in *Aquarelas*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aquarelas.conteudo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * Imagem destacada field in *Aquarelas*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aquarelas.imagem_destacada
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;

  /**
   * Número de referência field in *Aquarelas*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: aquarelas.numero_de_referencia
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  numero_de_referencia: prismic.NumberField;
}

/**
 * Aquarelas document from Prismic
 *
 * - **API ID**: `aquarelas`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AquarelasDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AquarelasDocumentData>,
    "aquarelas",
    Lang
  >;

/**
 * Content for Portfolio Category documents
 */
interface CategoryDocumentData {
  /**
   * Titulo field in *Portfolio Category*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtitulo field in *Portfolio Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.subtitulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo: prismic.KeyTextField;

  /**
   * Conteúdo field in *Portfolio Category*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.conteudo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * URL field in *Portfolio Category*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: category.url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkToMediaField;

  /**
   * Imagem destacada field in *Portfolio Category*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category.imagem_destacada
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;
}

/**
 * Portfolio Category document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    "category",
    Lang
  >;

type ComoComprarDocumentDataSlicesSlice =
  | HeroSlice
  | DepoimentosSlice
  | CasesPortfolioSlice
  | FormularioSlice
  | IntroComoComprarSlice
  | ComoTrabalhamosSlice;

/**
 * Content for Como comprar documents
 */
interface ComoComprarDocumentData {
  /**
   * Slice Zone field in *Como comprar*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: como_comprar.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ComoComprarDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Como comprar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: como_comprar.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Como comprar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: como_comprar.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Como comprar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: como_comprar.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Como comprar document from Prismic
 *
 * - **API ID**: `como_comprar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ComoComprarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ComoComprarDocumentData>,
    "como_comprar",
    Lang
  >;

type ContatoDocumentDataSlicesSlice = CasesPortfolioSlice | DepoimentosSlice;

/**
 * Content for Contato documents
 */
interface ContatoDocumentData {
  /**
   * Titulo field in *Contato*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtitulo field in *Contato*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.subtitulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * Conteúdo field in *Contato*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.conteudo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * Slice Zone field in *Contato*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContatoDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contato.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contato*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contato.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Contato document from Prismic
 *
 * - **API ID**: `contato`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContatoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContatoDocumentData>,
    "contato",
    Lang
  >;

/**
 * Content for Depoimento documents
 */
interface DepoimentoDocumentData {
  /**
   * Nome field in *Depoimento*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimento.nome
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  nome: prismic.RichTextField;

  /**
   * Foto field in *Depoimento*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimento.foto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto: prismic.ImageField<never>;

  /**
   * Conteúdo field in *Depoimento*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimento.conteudo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * Citação field in *Depoimento*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimento.citacao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  citacao: prismic.RichTextField;
}

/**
 * Depoimento document from Prismic
 *
 * - **API ID**: `depoimento`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DepoimentoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DepoimentoDocumentData>,
    "depoimento",
    Lang
  >;

type DepoimentosDocumentDataSlicesSlice =
  | DuasColunasSlice
  | CasesPortfolioSlice
  | FormularioSlice
  | HeroSlice
  | QuemSouEuSlice
  | DepoimentosSlice
  | DepoimentosEstrelasSlice;

/**
 * Content for Depoimentos documents
 */
interface DepoimentosDocumentData {
  /**
   * Slice Zone field in *Depoimentos*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimentos.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DepoimentosDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Depoimentos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: depoimentos.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Depoimentos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimentos.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Depoimentos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: depoimentos.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Depoimentos document from Prismic
 *
 * - **API ID**: `depoimentos`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DepoimentosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DepoimentosDocumentData>,
    "depoimentos",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | HeroSlice
  | DepoimentosSlice
  | QuemSouEuSlice
  | IntroHomeSlice
  | WhatsAppSlice
  | CasesPortfolioSlice
  | FormularioSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PaginaPortfolioDocumentDataSlicesSlice =
  | QuemSouEuSlice
  | WhatsAppSlice
  | CasesPortfolioSlice
  | FormularioSlice
  | HeroSlice;

/**
 * Content for Página Portfólio documents
 */
interface PaginaPortfolioDocumentData {
  /**
   * Slice Zone field in *Página Portfólio*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: pagina_portfolio.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PaginaPortfolioDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Página Portfólio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: pagina_portfolio.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Página Portfólio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pagina_portfolio.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Página Portfólio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: pagina_portfolio.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Página Portfólio document from Prismic
 *
 * - **API ID**: `pagina_portfolio`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PaginaPortfolioDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PaginaPortfolioDocumentData>,
    "pagina_portfolio",
    Lang
  >;

type PortfolioDocumentDataSlicesSlice =
  | DepoimentosSlice
  | FormularioSlice
  | HeroSlice
  | DetalhesProdutoSlice
  | OQueEstaInclusoSlice
  | ListaTodosTrabalhosSlice
  | GaleriaSlice;

/**
 * Content for Portfólio documents
 */
interface PortfolioDocumentData {
  /**
   * Título field in *Portfólio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Categoria field in *Portfólio*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.categoria
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  categoria: prismic.ContentRelationshipField<"portfolio_categoria">;

  /**
   * Imagem destacada field in *Portfólio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.imagem_destacada
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;

  /**
   * Conteúdo field in *Portfólio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.conteudo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * Slice Zone field in *Portfólio*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PortfolioDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Portfólio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: portfolio.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Portfólio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Portfólio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: portfolio.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Portfólio document from Prismic
 *
 * - **API ID**: `portfolio`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortfolioDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PortfolioDocumentData>,
    "portfolio",
    Lang
  >;

type PortfolioCategoriaDocumentDataSlicesSlice =
  | ListaTodosTrabalhosSlice
  | FormularioSlice
  | OQueEstaInclusoSlice
  | DepoimentosSlice
  | IntroQuemSomosSlice
  | DuasColunasSlice
  | GaleriaSlice
  | ListarAquarelasSlice;

/**
 * Content for Portfólio Categoria documents
 */
interface PortfolioCategoriaDocumentData {
  /**
   * Título field in *Portfólio Categoria*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_categoria.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtítulo field in *Portfólio Categoria*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_categoria.subtitulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo: prismic.KeyTextField;

  /**
   * Conteúdo field in *Portfólio Categoria*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_categoria.conteudo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * Imagem destacada field in *Portfólio Categoria*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_categoria.imagem_destacada
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;

  /**
   * Descrição field in *Portfólio Categoria*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_categoria.descricao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao: prismic.RichTextField;

  /**
   * Imagem background field in *Portfólio Categoria*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_categoria.imagem_background
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_background: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Portfólio Categoria*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_categoria.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PortfolioCategoriaDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Portfólio Categoria*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: portfolio_categoria.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Portfólio Categoria*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_categoria.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Portfólio Categoria*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: portfolio_categoria.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Portfólio Categoria document from Prismic
 *
 * - **API ID**: `portfolio_categoria`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortfolioCategoriaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PortfolioCategoriaDocumentData>,
    "portfolio_categoria",
    Lang
  >;

type QuemSomosDocumentDataSlicesSlice =
  | DepoimentosSlice
  | CasesPortfolioSlice
  | FormularioSlice
  | HeroSlice
  | IntroQuemSomosSlice
  | OurMottoSlice
  | QuemSomosImageSlice;

/**
 * Content for Quem somos documents
 */
interface QuemSomosDocumentData {
  /**
   * Slice Zone field in *Quem somos*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: quem_somos.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<QuemSomosDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Quem somos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: quem_somos.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Quem somos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: quem_somos.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Quem somos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: quem_somos.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Quem somos document from Prismic
 *
 * - **API ID**: `quem_somos`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type QuemSomosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<QuemSomosDocumentData>,
    "quem_somos",
    Lang
  >;

export type AllDocumentTypes =
  | AquarelasDocument
  | CategoryDocument
  | ComoComprarDocument
  | ContatoDocument
  | DepoimentoDocument
  | DepoimentosDocument
  | HomepageDocument
  | PaginaPortfolioDocument
  | PortfolioDocument
  | PortfolioCategoriaDocument
  | QuemSomosDocument;

/**
 * Primary content in *CasesPortfolio → Items*
 */
export interface CasesPortfolioSliceDefaultItem {
  /**
   * Categoria field in *CasesPortfolio → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_portfolio.items[].categoria
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  categoria: prismic.ContentRelationshipField<"portfolio_categoria">;
}

/**
 * Default variation for CasesPortfolio Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CasesPortfolioSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<CasesPortfolioSliceDefaultItem>
>;

/**
 * Slice variation for *CasesPortfolio*
 */
type CasesPortfolioSliceVariation = CasesPortfolioSliceDefault;

/**
 * CasesPortfolio Shared Slice
 *
 * - **API ID**: `cases_portfolio`
 * - **Description**: CasesPortfolio
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CasesPortfolioSlice = prismic.SharedSlice<
  "cases_portfolio",
  CasesPortfolioSliceVariation
>;

/**
 * Primary content in *ComoTrabalhamos → Primary*
 */
export interface ComoTrabalhamosSliceDefaultPrimary {
  /**
   * Número da seção field in *ComoTrabalhamos → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: como_trabalhamos.primary.numero_da_secao
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  numero_da_secao: prismic.NumberField;

  /**
   * Título field in *ComoTrabalhamos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: como_trabalhamos.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtítulo field in *ComoTrabalhamos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: como_trabalhamos.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * Conteúdo field in *ComoTrabalhamos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: como_trabalhamos.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * Imagem destacada field in *ComoTrabalhamos → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: como_trabalhamos.primary.imagem_destacada
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;
}

/**
 * Default variation for ComoTrabalhamos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ComoTrabalhamosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ComoTrabalhamosSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ComoTrabalhamos → Primary*
 */
export interface ComoTrabalhamosSliceUmaColunaPrimary {
  /**
   * Número da seção field in *ComoTrabalhamos → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: como_trabalhamos.primary.numero_da_secao
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  numero_da_secao: prismic.NumberField;

  /**
   * Título field in *ComoTrabalhamos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: como_trabalhamos.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtítulo field in *ComoTrabalhamos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: como_trabalhamos.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * Conteúdo field in *ComoTrabalhamos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: como_trabalhamos.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * Imagem destacada field in *ComoTrabalhamos → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: como_trabalhamos.primary.imagem_destacada
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;
}

/**
 * UmaColuna variation for ComoTrabalhamos Slice
 *
 * - **API ID**: `umaColuna`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ComoTrabalhamosSliceUmaColuna = prismic.SharedSliceVariation<
  "umaColuna",
  Simplify<ComoTrabalhamosSliceUmaColunaPrimary>,
  never
>;

/**
 * Primary content in *ComoTrabalhamos → Primary*
 */
export interface ComoTrabalhamosSliceDuasColunasPrimary {
  /**
   * Número da seção field in *ComoTrabalhamos → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: como_trabalhamos.primary.numero_da_secao
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  numero_da_secao: prismic.NumberField;

  /**
   * Título field in *ComoTrabalhamos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: como_trabalhamos.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtítulo field in *ComoTrabalhamos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: como_trabalhamos.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * Conteúdo field in *ComoTrabalhamos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: como_trabalhamos.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * Imagem destacada field in *ComoTrabalhamos → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: como_trabalhamos.primary.imagem_destacada
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;
}

/**
 * DuasColunas variation for ComoTrabalhamos Slice
 *
 * - **API ID**: `duasColunas`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ComoTrabalhamosSliceDuasColunas = prismic.SharedSliceVariation<
  "duasColunas",
  Simplify<ComoTrabalhamosSliceDuasColunasPrimary>,
  never
>;

/**
 * Slice variation for *ComoTrabalhamos*
 */
type ComoTrabalhamosSliceVariation =
  | ComoTrabalhamosSliceDefault
  | ComoTrabalhamosSliceUmaColuna
  | ComoTrabalhamosSliceDuasColunas;

/**
 * ComoTrabalhamos Shared Slice
 *
 * - **API ID**: `como_trabalhamos`
 * - **Description**: ComoTrabalhamos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ComoTrabalhamosSlice = prismic.SharedSlice<
  "como_trabalhamos",
  ComoTrabalhamosSliceVariation
>;

/**
 * Primary content in *Depoimentos → Primary*
 */
export interface DepoimentosSliceDefaultPrimary {
  /**
   * Título field in *Depoimentos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimentos.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;
}

/**
 * Primary content in *Depoimentos → Items*
 */
export interface DepoimentosSliceDefaultItem {
  /**
   * Depoimento field in *Depoimentos → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimentos.items[].depoimento
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  depoimento: prismic.ContentRelationshipField<"depoimento">;
}

/**
 * Default variation for Depoimentos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DepoimentosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DepoimentosSliceDefaultPrimary>,
  Simplify<DepoimentosSliceDefaultItem>
>;

/**
 * Primary content in *Depoimentos → Primary*
 */
export interface DepoimentosSliceCallToActionPrimary {
  /**
   * Titulo field in *Depoimentos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimentos.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Conteúdo field in *Depoimentos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimentos.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * URL field in *Depoimentos → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimentos.primary.url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;

  /**
   * Imagem destacada field in *Depoimentos → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimentos.primary.imagem_destacada
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;
}

/**
 * Call to action variation for Depoimentos Slice
 *
 * - **API ID**: `callToAction`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DepoimentosSliceCallToAction = prismic.SharedSliceVariation<
  "callToAction",
  Simplify<DepoimentosSliceCallToActionPrimary>,
  never
>;

/**
 * Primary content in *Depoimentos → Primary*
 */
export interface DepoimentosSliceTodosOsDepoimentosPrimary {
  /**
   * Título field in *Depoimentos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimentos.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;
}

/**
 * Todos os depoimentos variation for Depoimentos Slice
 *
 * - **API ID**: `todosOsDepoimentos`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DepoimentosSliceTodosOsDepoimentos = prismic.SharedSliceVariation<
  "todosOsDepoimentos",
  Simplify<DepoimentosSliceTodosOsDepoimentosPrimary>,
  never
>;

/**
 * Slice variation for *Depoimentos*
 */
type DepoimentosSliceVariation =
  | DepoimentosSliceDefault
  | DepoimentosSliceCallToAction
  | DepoimentosSliceTodosOsDepoimentos;

/**
 * Depoimentos Shared Slice
 *
 * - **API ID**: `depoimentos`
 * - **Description**: Depoimentos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DepoimentosSlice = prismic.SharedSlice<
  "depoimentos",
  DepoimentosSliceVariation
>;

/**
 * Default variation for DepoimentosEstrelas Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DepoimentosEstrelasSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *DepoimentosEstrelas*
 */
type DepoimentosEstrelasSliceVariation = DepoimentosEstrelasSliceDefault;

/**
 * DepoimentosEstrelas Shared Slice
 *
 * - **API ID**: `depoimentos_estrelas`
 * - **Description**: DepoimentosEstrelas
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DepoimentosEstrelasSlice = prismic.SharedSlice<
  "depoimentos_estrelas",
  DepoimentosEstrelasSliceVariation
>;

/**
 * Primary content in *DetalhesProduto → Primary*
 */
export interface DetalhesProdutoSliceDefaultPrimary {
  /**
   * Imagem destacada field in *DetalhesProduto → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: detalhes_produto.primary.imagem_destacada
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;

  /**
   * Envelope field in *DetalhesProduto → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detalhes_produto.primary.envelope
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  envelope: prismic.RichTextField;

  /**
   * Papel field in *DetalhesProduto → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detalhes_produto.primary.papel
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  papel: prismic.RichTextField;

  /**
   * Fecho field in *DetalhesProduto → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detalhes_produto.primary.fecho
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fecho: prismic.RichTextField;
}

/**
 * Default variation for DetalhesProduto Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DetalhesProdutoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DetalhesProdutoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DetalhesProduto*
 */
type DetalhesProdutoSliceVariation = DetalhesProdutoSliceDefault;

/**
 * DetalhesProduto Shared Slice
 *
 * - **API ID**: `detalhes_produto`
 * - **Description**: DetalhesProduto
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DetalhesProdutoSlice = prismic.SharedSlice<
  "detalhes_produto",
  DetalhesProdutoSliceVariation
>;

/**
 * Primary content in *DuasColunas → Primary*
 */
export interface DuasColunasSliceDefaultPrimary {
  /**
   * Título field in *DuasColunas → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: duas_colunas.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtitulo field in *DuasColunas → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: duas_colunas.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * Conteúdo field in *DuasColunas → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: duas_colunas.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;
}

/**
 * Default variation for DuasColunas Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DuasColunasSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DuasColunasSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DuasColunas*
 */
type DuasColunasSliceVariation = DuasColunasSliceDefault;

/**
 * DuasColunas Shared Slice
 *
 * - **API ID**: `duas_colunas`
 * - **Description**: DuasColunas
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DuasColunasSlice = prismic.SharedSlice<
  "duas_colunas",
  DuasColunasSliceVariation
>;

/**
 * Primary content in *Formulario → Primary*
 */
export interface FormularioSliceDefaultPrimary {
  /**
   * Titulo field in *Formulario → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formulario.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtitulo field in *Formulario → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formulario.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * Conteudo field in *Formulario → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formulario.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;
}

/**
 * Default variation for Formulario Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormularioSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormularioSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Formulario → Primary*
 */
export interface FormularioSliceOrcamentoPrimary {
  /**
   * Titulo field in *Formulario → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formulario.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtitulo field in *Formulario → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formulario.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * Conteudo field in *Formulario → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formulario.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;
}

/**
 * Orçamento variation for Formulario Slice
 *
 * - **API ID**: `orcamento`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormularioSliceOrcamento = prismic.SharedSliceVariation<
  "orcamento",
  Simplify<FormularioSliceOrcamentoPrimary>,
  never
>;

/**
 * Primary content in *Formulario → Primary*
 */
export interface FormularioSliceOrcamentoProdutoPrimary {
  /**
   * Titulo field in *Formulario → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formulario.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtitulo field in *Formulario → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formulario.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * Conteudo field in *Formulario → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formulario.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * Style field in *Formulario → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: pink
   * - **API ID Path**: formulario.primary.style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  style: prismic.SelectField<"pink" | "black", "filled">;
}

/**
 * Orçamento - Produto variation for Formulario Slice
 *
 * - **API ID**: `orcamentoProduto`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormularioSliceOrcamentoProduto = prismic.SharedSliceVariation<
  "orcamentoProduto",
  Simplify<FormularioSliceOrcamentoProdutoPrimary>,
  never
>;

/**
 * Slice variation for *Formulario*
 */
type FormularioSliceVariation =
  | FormularioSliceDefault
  | FormularioSliceOrcamento
  | FormularioSliceOrcamentoProduto;

/**
 * Formulario Shared Slice
 *
 * - **API ID**: `formulario`
 * - **Description**: Formulario
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormularioSlice = prismic.SharedSlice<
  "formulario",
  FormularioSliceVariation
>;

/**
 * Primary content in *Galeria → Primary*
 */
export interface GaleriaSliceDefaultPrimary {
  /**
   * Galeria layout field in *Galeria → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: rows
   * - **API ID Path**: galeria.primary.galeria_layout
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  galeria_layout: prismic.SelectField<"rows" | "columns" | "masonry", "filled">;

  /**
   * Título field in *Galeria → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: galeria.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Conteúdo field in *Galeria → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: galeria.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;
}

/**
 * Primary content in *Galeria → Items*
 */
export interface GaleriaSliceDefaultItem {
  /**
   * Imagem field in *Galeria → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: galeria.items[].imagem
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem: prismic.ImageField<never>;
}

/**
 * Default variation for Galeria Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GaleriaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GaleriaSliceDefaultPrimary>,
  Simplify<GaleriaSliceDefaultItem>
>;

/**
 * Slice variation for *Galeria*
 */
type GaleriaSliceVariation = GaleriaSliceDefault;

/**
 * Galeria Shared Slice
 *
 * - **API ID**: `galeria`
 * - **Description**: Galeria
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GaleriaSlice = prismic.SharedSlice<
  "galeria",
  GaleriaSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Titulo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtitulo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * Imagem destacada field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.imagem_destacada
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;

  /**
   * Conteúdo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceHomePrimary {
  /**
   * Titulo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtitulo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * Imagem destacada field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.imagem_destacada
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;

  /**
   * Conteúdo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;
}

/**
 * Home variation for Hero Slice
 *
 * - **API ID**: `home`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceHome = prismic.SharedSliceVariation<
  "home",
  Simplify<HeroSliceHomePrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceComoComprarPrimary {
  /**
   * Titulo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtitulo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * Imagem destacada field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.imagem_destacada
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;

  /**
   * Conteúdo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;
}

/**
 * Como Comprar variation for Hero Slice
 *
 * - **API ID**: `comoComprar`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceComoComprar = prismic.SharedSliceVariation<
  "comoComprar",
  Simplify<HeroSliceComoComprarPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceQuemSomosPrimary {
  /**
   * Titulo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Conteúdo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * Video completo field in *Hero → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.video_completo
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video_completo: prismic.LinkToMediaField;

  /**
   * Video chamada field in *Hero → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.video_chamada
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video_chamada: prismic.LinkToMediaField;
}

/**
 * Quem Somos variation for Hero Slice
 *
 * - **API ID**: `quemSomos`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceQuemSomos = prismic.SharedSliceVariation<
  "quemSomos",
  Simplify<HeroSliceQuemSomosPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSlicePaginaPortfolioPrimary {
  /**
   * Titulo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtitulo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * Imagem destacada field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.imagem_destacada
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;

  /**
   * Conteúdo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;
}

/**
 * Página Portfólio variation for Hero Slice
 *
 * - **API ID**: `paginaPortfolio`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlicePaginaPortfolio = prismic.SharedSliceVariation<
  "paginaPortfolio",
  Simplify<HeroSlicePaginaPortfolioPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation =
  | HeroSliceDefault
  | HeroSliceHome
  | HeroSliceComoComprar
  | HeroSliceQuemSomos
  | HeroSlicePaginaPortfolio;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *IntroComoComprar → Primary*
 */
export interface IntroComoComprarSliceDefaultPrimary {
  /**
   * Imagem destacada field in *IntroComoComprar → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_como_comprar.primary.imagem_destacada
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;
}

/**
 * Default variation for IntroComoComprar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroComoComprarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntroComoComprarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IntroComoComprar*
 */
type IntroComoComprarSliceVariation = IntroComoComprarSliceDefault;

/**
 * IntroComoComprar Shared Slice
 *
 * - **API ID**: `intro_como_comprar`
 * - **Description**: IntroComoComprar
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroComoComprarSlice = prismic.SharedSlice<
  "intro_como_comprar",
  IntroComoComprarSliceVariation
>;

/**
 * Primary content in *IntroHome → Primary*
 */
export interface IntroHomeSliceDefaultPrimary {
  /**
   * Titulo field in *IntroHome → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_home.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Conteúdo field in *IntroHome → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_home.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * URL field in *IntroHome → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_home.primary.url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;

  /**
   * Imagem d field in *IntroHome → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_home.primary.imagem_destacada
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;
}

/**
 * Default variation for IntroHome Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroHomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntroHomeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IntroHome*
 */
type IntroHomeSliceVariation = IntroHomeSliceDefault;

/**
 * IntroHome Shared Slice
 *
 * - **API ID**: `intro_home`
 * - **Description**: IntroHome
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroHomeSlice = prismic.SharedSlice<
  "intro_home",
  IntroHomeSliceVariation
>;

/**
 * Primary content in *IntroQuemSomos → Primary*
 */
export interface IntroQuemSomosSliceDefaultPrimary {
  /**
   * Título field in *IntroQuemSomos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_quem_somos.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtítulo field in *IntroQuemSomos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_quem_somos.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * Conteúdo field in *IntroQuemSomos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_quem_somos.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * Citação field in *IntroQuemSomos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_quem_somos.primary.citacao
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  citacao: prismic.RichTextField;
}

/**
 * Default variation for IntroQuemSomos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroQuemSomosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntroQuemSomosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IntroQuemSomos*
 */
type IntroQuemSomosSliceVariation = IntroQuemSomosSliceDefault;

/**
 * IntroQuemSomos Shared Slice
 *
 * - **API ID**: `intro_quem_somos`
 * - **Description**: IntroQuemSomos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroQuemSomosSlice = prismic.SharedSlice<
  "intro_quem_somos",
  IntroQuemSomosSliceVariation
>;

/**
 * Primary content in *ListaTodosTrabalhos → Primary*
 */
export interface ListaTodosTrabalhosSliceDefaultPrimary {
  /**
   * Título field in *ListaTodosTrabalhos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lista_todos_trabalhos.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Portfólio categoria field in *ListaTodosTrabalhos → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: lista_todos_trabalhos.primary.portfolio_categoria
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  portfolio_categoria: prismic.ContentRelationshipField<"portfolio_categoria">;
}

/**
 * Default variation for ListaTodosTrabalhos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListaTodosTrabalhosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ListaTodosTrabalhosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ListaTodosTrabalhos*
 */
type ListaTodosTrabalhosSliceVariation = ListaTodosTrabalhosSliceDefault;

/**
 * ListaTodosTrabalhos Shared Slice
 *
 * - **API ID**: `lista_todos_trabalhos`
 * - **Description**: ListaTodosTrabalhos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListaTodosTrabalhosSlice = prismic.SharedSlice<
  "lista_todos_trabalhos",
  ListaTodosTrabalhosSliceVariation
>;

/**
 * Primary content in *ListarAquarelas → Primary*
 */
export interface ListarAquarelasSliceDefaultPrimary {
  /**
   * Título field in *ListarAquarelas → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: listar_aquarelas.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Conteúdo field in *ListarAquarelas → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: listar_aquarelas.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;
}

/**
 * Primary content in *ListarAquarelas → Items*
 */
export interface ListarAquarelasSliceDefaultItem {
  /**
   * Aquarela field in *ListarAquarelas → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: listar_aquarelas.items[].aquarela
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  aquarela: prismic.ContentRelationshipField;
}

/**
 * Default variation for ListarAquarelas Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListarAquarelasSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ListarAquarelasSliceDefaultPrimary>,
  Simplify<ListarAquarelasSliceDefaultItem>
>;

/**
 * Slice variation for *ListarAquarelas*
 */
type ListarAquarelasSliceVariation = ListarAquarelasSliceDefault;

/**
 * ListarAquarelas Shared Slice
 *
 * - **API ID**: `listar_aquarelas`
 * - **Description**: ListarAquarelas
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListarAquarelasSlice = prismic.SharedSlice<
  "listar_aquarelas",
  ListarAquarelasSliceVariation
>;

/**
 * Default variation for OQueEstaIncluso Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OQueEstaInclusoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Signature variation for OQueEstaIncluso Slice
 *
 * - **API ID**: `signature`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OQueEstaInclusoSliceSignature = prismic.SharedSliceVariation<
  "signature",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *OQueEstaIncluso*
 */
type OQueEstaInclusoSliceVariation =
  | OQueEstaInclusoSliceDefault
  | OQueEstaInclusoSliceSignature;

/**
 * OQueEstaIncluso Shared Slice
 *
 * - **API ID**: `o_que_esta_incluso`
 * - **Description**: OQueEstaIncluso
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OQueEstaInclusoSlice = prismic.SharedSlice<
  "o_que_esta_incluso",
  OQueEstaInclusoSliceVariation
>;

/**
 * Primary content in *OurMotto → Primary*
 */
export interface OurMottoSliceDefaultPrimary {
  /**
   * Vídeo field in *OurMotto → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: our_motto.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField;

  /**
   * Citação field in *OurMotto → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_motto.primary.citacao
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  citacao: prismic.RichTextField;

  /**
   * Autor field in *OurMotto → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_motto.primary.autor
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  autor: prismic.RichTextField;
}

/**
 * Default variation for OurMotto Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurMottoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurMottoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OurMotto*
 */
type OurMottoSliceVariation = OurMottoSliceDefault;

/**
 * OurMotto Shared Slice
 *
 * - **API ID**: `our_motto`
 * - **Description**: OurMotto
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurMottoSlice = prismic.SharedSlice<
  "our_motto",
  OurMottoSliceVariation
>;

/**
 * Primary content in *QuemSomosImage → Primary*
 */
export interface QuemSomosImageSliceDefaultPrimary {
  /**
   * Imagem destacada field in *QuemSomosImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: quem_somos_image.primary.imagem_destacada
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;

  /**
   * Conteúdo field in *QuemSomosImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quem_somos_image.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;
}

/**
 * Default variation for QuemSomosImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuemSomosImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuemSomosImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *QuemSomosImage*
 */
type QuemSomosImageSliceVariation = QuemSomosImageSliceDefault;

/**
 * QuemSomosImage Shared Slice
 *
 * - **API ID**: `quem_somos_image`
 * - **Description**: QuemSomosImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuemSomosImageSlice = prismic.SharedSlice<
  "quem_somos_image",
  QuemSomosImageSliceVariation
>;

/**
 * Primary content in *QuemSouEu → Primary*
 */
export interface QuemSouEuSliceDefaultPrimary {
  /**
   * Titulo field in *QuemSouEu → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quem_sou_eu.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtitulo field in *QuemSouEu → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quem_sou_eu.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * Conteúdo field in *QuemSouEu → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quem_sou_eu.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * URL field in *QuemSouEu → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: quem_sou_eu.primary.url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;

  /**
   * Imagem destacada field in *QuemSouEu → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: quem_sou_eu.primary.imagem_de
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_de: prismic.ImageField<never>;
}

/**
 * Default variation for QuemSouEu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuemSouEuSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuemSouEuSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *QuemSouEu*
 */
type QuemSouEuSliceVariation = QuemSouEuSliceDefault;

/**
 * QuemSouEu Shared Slice
 *
 * - **API ID**: `quem_sou_eu`
 * - **Description**: QuemSouEu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuemSouEuSlice = prismic.SharedSlice<
  "quem_sou_eu",
  QuemSouEuSliceVariation
>;

/**
 * Primary content in *WhatsApp → Primary*
 */
export interface WhatsAppSliceDefaultPrimary {
  /**
   * Titulo field in *WhatsApp → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whats_app.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Conteúdo field in *WhatsApp → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whats_app.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * URL WhatsApp field in *WhatsApp → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whats_app.primary.url_whatsapp
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  url_whatsapp: prismic.KeyTextField;

  /**
   * Imagem destacada field in *WhatsApp → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: whats_app.primary.imagem_destacada
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;
}

/**
 * Default variation for WhatsApp Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhatsAppSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhatsAppSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhatsApp*
 */
type WhatsAppSliceVariation = WhatsAppSliceDefault;

/**
 * WhatsApp Shared Slice
 *
 * - **API ID**: `whats_app`
 * - **Description**: WhatsApp
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhatsAppSlice = prismic.SharedSlice<
  "whats_app",
  WhatsAppSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AquarelasDocument,
      AquarelasDocumentData,
      CategoryDocument,
      CategoryDocumentData,
      ComoComprarDocument,
      ComoComprarDocumentData,
      ContatoDocument,
      ContatoDocumentData,
      DepoimentoDocument,
      DepoimentoDocumentData,
      DepoimentosDocument,
      DepoimentosDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      PaginaPortfolioDocument,
      PaginaPortfolioDocumentData,
      PortfolioDocument,
      PortfolioDocumentData,
      PortfolioCategoriaDocument,
      PortfolioCategoriaDocumentData,
      QuemSomosDocument,
      QuemSomosDocumentData,
      AllDocumentTypes,
      CasesPortfolioSlice,
      CasesPortfolioSliceVariation,
      CasesPortfolioSliceDefault,
      ComoTrabalhamosSlice,
      ComoTrabalhamosSliceVariation,
      ComoTrabalhamosSliceDefault,
      ComoTrabalhamosSliceUmaColuna,
      ComoTrabalhamosSliceDuasColunas,
      DepoimentosSlice,
      DepoimentosSliceVariation,
      DepoimentosSliceDefault,
      DepoimentosSliceCallToAction,
      DepoimentosSliceTodosOsDepoimentos,
      DepoimentosEstrelasSlice,
      DepoimentosEstrelasSliceVariation,
      DepoimentosEstrelasSliceDefault,
      DetalhesProdutoSlice,
      DetalhesProdutoSliceVariation,
      DetalhesProdutoSliceDefault,
      DuasColunasSlice,
      DuasColunasSliceVariation,
      DuasColunasSliceDefault,
      FormularioSlice,
      FormularioSliceVariation,
      FormularioSliceDefault,
      FormularioSliceOrcamento,
      FormularioSliceOrcamentoProduto,
      GaleriaSlice,
      GaleriaSliceVariation,
      GaleriaSliceDefault,
      HeroSlice,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceHome,
      HeroSliceComoComprar,
      HeroSliceQuemSomos,
      HeroSlicePaginaPortfolio,
      IntroComoComprarSlice,
      IntroComoComprarSliceVariation,
      IntroComoComprarSliceDefault,
      IntroHomeSlice,
      IntroHomeSliceVariation,
      IntroHomeSliceDefault,
      IntroQuemSomosSlice,
      IntroQuemSomosSliceVariation,
      IntroQuemSomosSliceDefault,
      ListaTodosTrabalhosSlice,
      ListaTodosTrabalhosSliceVariation,
      ListaTodosTrabalhosSliceDefault,
      ListarAquarelasSlice,
      ListarAquarelasSliceVariation,
      ListarAquarelasSliceDefault,
      OQueEstaInclusoSlice,
      OQueEstaInclusoSliceVariation,
      OQueEstaInclusoSliceDefault,
      OQueEstaInclusoSliceSignature,
      OurMottoSlice,
      OurMottoSliceVariation,
      OurMottoSliceDefault,
      QuemSomosImageSlice,
      QuemSomosImageSliceVariation,
      QuemSomosImageSliceDefault,
      QuemSouEuSlice,
      QuemSouEuSliceVariation,
      QuemSouEuSliceDefault,
      WhatsAppSlice,
      WhatsAppSliceVariation,
      WhatsAppSliceDefault,
    };
  }
}
