// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice =
  | HeroSlice
  | DepoimentosSlice
  | QuemSouEuSlice
  | IntroHomeSlice
  | WhatsAppSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Default variation for Depoimentos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DepoimentosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Primary content in *Depoimentos → Primary*
 */
export interface DepoimentosSliceCallToActionPrimary {
  /**
   * Titulo field in *Depoimentos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimentos.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Conteúdo field in *Depoimentos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimentos.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * URL field in *Depoimentos → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimentos.primary.url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;

  /**
   * Imagem destacada field in *Depoimentos → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: depoimentos.primary.imagem_destacada
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;
}

/**
 * Call to action variation for Depoimentos Slice
 *
 * - **API ID**: `callToAction`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DepoimentosSliceCallToAction = prismic.SharedSliceVariation<
  "callToAction",
  Simplify<DepoimentosSliceCallToActionPrimary>,
  never
>;

/**
 * Slice variation for *Depoimentos*
 */
type DepoimentosSliceVariation =
  | DepoimentosSliceDefault
  | DepoimentosSliceCallToAction;

/**
 * Depoimentos Shared Slice
 *
 * - **API ID**: `depoimentos`
 * - **Description**: Depoimentos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DepoimentosSlice = prismic.SharedSlice<
  "depoimentos",
  DepoimentosSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Titulo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtitulo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * Imagem destacada field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.imagem_destacada
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;

  /**
   * Conteúdo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceHomePrimary {
  /**
   * Titulo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtitulo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * Imagem destacada field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.imagem_destacada
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;

  /**
   * Conteúdo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;
}

/**
 * Home variation for Hero Slice
 *
 * - **API ID**: `home`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceHome = prismic.SharedSliceVariation<
  "home",
  Simplify<HeroSliceHomePrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceHome;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *IntroHome → Primary*
 */
export interface IntroHomeSliceDefaultPrimary {
  /**
   * Titulo field in *IntroHome → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_home.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Conteúdo field in *IntroHome → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_home.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * URL field in *IntroHome → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_home.primary.url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;

  /**
   * Imagem d field in *IntroHome → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_home.primary.imagem_destacada
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;
}

/**
 * Default variation for IntroHome Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroHomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntroHomeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IntroHome*
 */
type IntroHomeSliceVariation = IntroHomeSliceDefault;

/**
 * IntroHome Shared Slice
 *
 * - **API ID**: `intro_home`
 * - **Description**: IntroHome
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroHomeSlice = prismic.SharedSlice<
  "intro_home",
  IntroHomeSliceVariation
>;

/**
 * Primary content in *QuemSouEu → Primary*
 */
export interface QuemSouEuSliceDefaultPrimary {
  /**
   * Titulo field in *QuemSouEu → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quem_sou_eu.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Subtitulo field in *QuemSouEu → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quem_sou_eu.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitulo: prismic.RichTextField;

  /**
   * Conteúdo field in *QuemSouEu → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quem_sou_eu.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * URL field in *QuemSouEu → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: quem_sou_eu.primary.url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;

  /**
   * Imagem destacada field in *QuemSouEu → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: quem_sou_eu.primary.imagem_de
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_de: prismic.ImageField<never>;
}

/**
 * Default variation for QuemSouEu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuemSouEuSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuemSouEuSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *QuemSouEu*
 */
type QuemSouEuSliceVariation = QuemSouEuSliceDefault;

/**
 * QuemSouEu Shared Slice
 *
 * - **API ID**: `quem_sou_eu`
 * - **Description**: QuemSouEu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuemSouEuSlice = prismic.SharedSlice<
  "quem_sou_eu",
  QuemSouEuSliceVariation
>;

/**
 * Primary content in *WhatsApp → Primary*
 */
export interface WhatsAppSliceDefaultPrimary {
  /**
   * Titulo field in *WhatsApp → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whats_app.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.RichTextField;

  /**
   * Conteúdo field in *WhatsApp → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whats_app.primary.conteudo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * URL WhatsApp field in *WhatsApp → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whats_app.primary.url_whatsapp
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  url_whatsapp: prismic.KeyTextField;

  /**
   * Imagem destacada field in *WhatsApp → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: whats_app.primary.imagem_destacada
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_destacada: prismic.ImageField<never>;
}

/**
 * Default variation for WhatsApp Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhatsAppSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhatsAppSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhatsApp*
 */
type WhatsAppSliceVariation = WhatsAppSliceDefault;

/**
 * WhatsApp Shared Slice
 *
 * - **API ID**: `whats_app`
 * - **Description**: WhatsApp
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhatsAppSlice = prismic.SharedSlice<
  "whats_app",
  WhatsAppSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      AllDocumentTypes,
      DepoimentosSlice,
      DepoimentosSliceVariation,
      DepoimentosSliceDefault,
      DepoimentosSliceCallToAction,
      HeroSlice,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceHome,
      IntroHomeSlice,
      IntroHomeSliceVariation,
      IntroHomeSliceDefault,
      QuemSouEuSlice,
      QuemSouEuSliceVariation,
      QuemSouEuSliceDefault,
      WhatsAppSlice,
      WhatsAppSliceVariation,
      WhatsAppSliceDefault,
    };
  }
}
