// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cases_portfolio: dynamic(() => import("./CasesPortfolio")),
  como_trabalhamos: dynamic(() => import("./ComoTrabalhamos")),
  depoimentos: dynamic(() => import("./Depoimentos")),
  detalhes_produto: dynamic(() => import("./DetalhesProduto")),
  duas_colunas: dynamic(() => import("./DuasColunas")),
  formulario: dynamic(() => import("./Formulario")),
  galeria: dynamic(() => import("./Galeria")),
  hero: dynamic(() => import("./Hero")),
  intro_como_comprar: dynamic(() => import("./IntroComoComprar")),
  intro_home: dynamic(() => import("./IntroHome")),
  intro_quem_somos: dynamic(() => import("./IntroQuemSomos")),
  lista_todos_trabalhos: dynamic(() => import("./ListaTodosTrabalhos")),
  o_que_esta_incluso: dynamic(() => import("./OQueEstaIncluso")),
  our_motto: dynamic(() => import("./OurMotto")),
  quem_somos_image: dynamic(() => import("./QuemSomosImage")),
  quem_sou_eu: dynamic(() => import("./QuemSouEu")),
  whats_app: dynamic(() => import("./WhatsApp")),
};
