// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cases_portfolio: dynamic(() => import("./CasesPortfolio")),
  depoimentos: dynamic(() => import("./Depoimentos")),
  formulario: dynamic(() => import("./Formulario")),
  hero: dynamic(() => import("./Hero")),
  intro_home: dynamic(() => import("./IntroHome")),
  quem_sou_eu: dynamic(() => import("./QuemSouEu")),
  whats_app: dynamic(() => import("./WhatsApp")),
};
